class Config:
    THAW_SWARMS = False
    NUMBER_POINTS = 94
    INITIAL_RANGE = 2
    MAX_RANGE = 30
    DROP_PROB_SENDER = 0
    DROP_PROB_RECEIVER = 0
    STATE_TIMEOUT = 5
    FLS_SPEED = 15
    DEAD_RECKONING_ANGLE = 1
